language: r
cache: packages

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r: release
    - os: linux
      r: devel

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
